chore(ci/cd): configure ci/cd pipeline to work in qa environment

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -117,6 +117,19 @@ jobs:
           # Como usamos --ignore-scripts por seguridad, ejecutamos patch-package manualmente
           ./node_modules/.bin/patch-package
 
+      - name: Inject QA Firebase Configuration
+        if: github.ref == 'refs/heads/qa'
+        env:
+          FIREBASE_QA_BASE64: ${{ secrets.ANDROID_FIREBASE_QA_JSON_BASE64 }}
+        run: |
+          if [ -z "$FIREBASE_QA_BASE64" ]; then
+            echo "::error::El secreto ANDROID_FIREBASE_QA_JSON_BASE64 no está configurado en GitHub."
+            exit 1
+          else
+            echo "Decodificando e inyectando configuración de Firebase para QA..."
+            echo "$FIREBASE_QA_BASE64" | base64 --decode > ./google-services.json
+          fi
+
       - name: Setup Expo and EAS CLI
         uses: expo/expo-github-action@c7b66a9c327a43a8fa7c0158e7f30d6040d2481e # v8
         with:
